# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Qt\Qt5.12\6.5.2\Src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Qt\Qt5.12\6.5.2\Src\qtbase\src\plugins\sqldrivers

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@echo Running external command ...
	"C:\Program Files\CMake\bin\ctest.exe" --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@echo Running external command ...
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo Running external command ...
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@echo Running external command ...
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@echo Running external command ...
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo Running external command ...
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@echo Running external command ...
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@echo Running external command ...
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@echo Running external command ...
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@echo Running external command ...
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Qt\Qt5.12\6.5.2\Src\qtbase\src\plugins\sqldrivers\CMakeFiles C:\Qt\Qt5.12\6.5.2\Src\qtbase\src\plugins\sqldrivers\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Qt\Qt5.12\6.5.2\Src\qtbase\src\plugins\sqldrivers\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\docs.dir\build.make qtbase/CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named prepare_docs

# Build rule for target.
prepare_docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 prepare_docs
.PHONY : prepare_docs

# fast build rule for target.
prepare_docs/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\prepare_docs.dir\build.make qtbase/CMakeFiles/prepare_docs.dir/build
.PHONY : prepare_docs/fast

#=============================================================================
# Target rules for targets named generate_docs

# Build rule for target.
generate_docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 generate_docs
.PHONY : generate_docs

# fast build rule for target.
generate_docs/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\generate_docs.dir\build.make qtbase/CMakeFiles/generate_docs.dir/build
.PHONY : generate_docs/fast

#=============================================================================
# Target rules for targets named html_docs

# Build rule for target.
html_docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 html_docs
.PHONY : html_docs

# fast build rule for target.
html_docs/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\html_docs.dir\build.make qtbase/CMakeFiles/html_docs.dir/build
.PHONY : html_docs/fast

#=============================================================================
# Target rules for targets named qch_docs

# Build rule for target.
qch_docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qch_docs
.PHONY : qch_docs

# fast build rule for target.
qch_docs/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\qch_docs.dir\build.make qtbase/CMakeFiles/qch_docs.dir/build
.PHONY : qch_docs/fast

#=============================================================================
# Target rules for targets named install_html_docs

# Build rule for target.
install_html_docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 install_html_docs
.PHONY : install_html_docs

# fast build rule for target.
install_html_docs/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\install_html_docs.dir\build.make qtbase/CMakeFiles/install_html_docs.dir/build
.PHONY : install_html_docs/fast

#=============================================================================
# Target rules for targets named install_qch_docs

# Build rule for target.
install_qch_docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 install_qch_docs
.PHONY : install_qch_docs

# fast build rule for target.
install_qch_docs/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\install_qch_docs.dir\build.make qtbase/CMakeFiles/install_qch_docs.dir/build
.PHONY : install_qch_docs/fast

#=============================================================================
# Target rules for targets named install_docs

# Build rule for target.
install_docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 install_docs
.PHONY : install_docs

# fast build rule for target.
install_docs/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\install_docs.dir\build.make qtbase/CMakeFiles/install_docs.dir/build
.PHONY : install_docs/fast

#=============================================================================
# Target rules for targets named sync_headers

# Build rule for target.
sync_headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sync_headers
.PHONY : sync_headers

# fast build rule for target.
sync_headers/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\sync_headers.dir\build.make qtbase/CMakeFiles/sync_headers.dir/build
.PHONY : sync_headers/fast

#=============================================================================
# Target rules for targets named thirdparty_sync_headers

# Build rule for target.
thirdparty_sync_headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 thirdparty_sync_headers
.PHONY : thirdparty_sync_headers

# fast build rule for target.
thirdparty_sync_headers/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\thirdparty_sync_headers.dir\build.make qtbase/CMakeFiles/thirdparty_sync_headers.dir/build
.PHONY : thirdparty_sync_headers/fast

#=============================================================================
# Target rules for targets named qt_plugins

# Build rule for target.
qt_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qt_plugins
.PHONY : qt_plugins

# fast build rule for target.
qt_plugins/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\qt_plugins.dir\build.make qtbase/CMakeFiles/qt_plugins.dir/build
.PHONY : qt_plugins/fast

#=============================================================================
# Target rules for targets named qpa_plugins

# Build rule for target.
qpa_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qpa_plugins
.PHONY : qpa_plugins

# fast build rule for target.
qpa_plugins/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\qpa_plugins.dir\build.make qtbase/CMakeFiles/qpa_plugins.dir/build
.PHONY : qpa_plugins/fast

#=============================================================================
# Target rules for targets named qpa_default_plugins

# Build rule for target.
qpa_default_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qpa_default_plugins
.PHONY : qpa_default_plugins

# fast build rule for target.
qpa_default_plugins/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\qpa_default_plugins.dir\build.make qtbase/CMakeFiles/qpa_default_plugins.dir/build
.PHONY : qpa_default_plugins/fast

#=============================================================================
# Target rules for targets named qt_plugins_qtbase

# Build rule for target.
qt_plugins_qtbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qt_plugins_qtbase
.PHONY : qt_plugins_qtbase

# fast build rule for target.
qt_plugins_qtbase/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\qt_plugins_qtbase.dir\build.make qtbase/CMakeFiles/qt_plugins_qtbase.dir/build
.PHONY : qt_plugins_qtbase/fast

#=============================================================================
# Target rules for targets named qt_plugins_qtbase_recursive

# Build rule for target.
qt_plugins_qtbase_recursive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qt_plugins_qtbase_recursive
.PHONY : qt_plugins_qtbase_recursive

# fast build rule for target.
qt_plugins_qtbase_recursive/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\qt_plugins_qtbase_recursive.dir\build.make qtbase/CMakeFiles/qt_plugins_qtbase_recursive.dir/build
.PHONY : qt_plugins_qtbase_recursive/fast

#=============================================================================
# Target rules for targets named docs_qtbase

# Build rule for target.
docs_qtbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 docs_qtbase
.PHONY : docs_qtbase

# fast build rule for target.
docs_qtbase/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\docs_qtbase.dir\build.make qtbase/CMakeFiles/docs_qtbase.dir/build
.PHONY : docs_qtbase/fast

#=============================================================================
# Target rules for targets named prepare_docs_qtbase

# Build rule for target.
prepare_docs_qtbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 prepare_docs_qtbase
.PHONY : prepare_docs_qtbase

# fast build rule for target.
prepare_docs_qtbase/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\prepare_docs_qtbase.dir\build.make qtbase/CMakeFiles/prepare_docs_qtbase.dir/build
.PHONY : prepare_docs_qtbase/fast

#=============================================================================
# Target rules for targets named generate_docs_qtbase

# Build rule for target.
generate_docs_qtbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 generate_docs_qtbase
.PHONY : generate_docs_qtbase

# fast build rule for target.
generate_docs_qtbase/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\generate_docs_qtbase.dir\build.make qtbase/CMakeFiles/generate_docs_qtbase.dir/build
.PHONY : generate_docs_qtbase/fast

#=============================================================================
# Target rules for targets named qch_docs_qtbase

# Build rule for target.
qch_docs_qtbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qch_docs_qtbase
.PHONY : qch_docs_qtbase

# fast build rule for target.
qch_docs_qtbase/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\qch_docs_qtbase.dir\build.make qtbase/CMakeFiles/qch_docs_qtbase.dir/build
.PHONY : qch_docs_qtbase/fast

#=============================================================================
# Target rules for targets named html_docs_qtbase

# Build rule for target.
html_docs_qtbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 html_docs_qtbase
.PHONY : html_docs_qtbase

# fast build rule for target.
html_docs_qtbase/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\html_docs_qtbase.dir\build.make qtbase/CMakeFiles/html_docs_qtbase.dir/build
.PHONY : html_docs_qtbase/fast

#=============================================================================
# Target rules for targets named install_html_docs_qtbase

# Build rule for target.
install_html_docs_qtbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 install_html_docs_qtbase
.PHONY : install_html_docs_qtbase

# fast build rule for target.
install_html_docs_qtbase/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\install_html_docs_qtbase.dir\build.make qtbase/CMakeFiles/install_html_docs_qtbase.dir/build
.PHONY : install_html_docs_qtbase/fast

#=============================================================================
# Target rules for targets named install_qch_docs_qtbase

# Build rule for target.
install_qch_docs_qtbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 install_qch_docs_qtbase
.PHONY : install_qch_docs_qtbase

# fast build rule for target.
install_qch_docs_qtbase/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\install_qch_docs_qtbase.dir\build.make qtbase/CMakeFiles/install_qch_docs_qtbase.dir/build
.PHONY : install_qch_docs_qtbase/fast

#=============================================================================
# Target rules for targets named install_docs_qtbase

# Build rule for target.
install_docs_qtbase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 install_docs_qtbase
.PHONY : install_docs_qtbase

# fast build rule for target.
install_docs_qtbase/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\install_docs_qtbase.dir\build.make qtbase/CMakeFiles/install_docs_qtbase.dir/build
.PHONY : install_docs_qtbase/fast

#=============================================================================
# Target rules for targets named host_tools

# Build rule for target.
host_tools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 host_tools
.PHONY : host_tools

# fast build rule for target.
host_tools/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\host_tools.dir\build.make qtbase/CMakeFiles/host_tools.dir/build
.PHONY : host_tools/fast

#=============================================================================
# Target rules for targets named bootstrap_tools

# Build rule for target.
bootstrap_tools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 bootstrap_tools
.PHONY : bootstrap_tools

# fast build rule for target.
bootstrap_tools/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\bootstrap_tools.dir\build.make qtbase/CMakeFiles/bootstrap_tools.dir/build
.PHONY : bootstrap_tools/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\benchmark.dir\build.make qtbase/CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named qmodule_pri

# Build rule for target.
qmodule_pri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 qmodule_pri
.PHONY : qmodule_pri

# fast build rule for target.
qmodule_pri/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\CMakeFiles\qmodule_pri.dir\build.make qtbase/CMakeFiles/qmodule_pri.dir/build
.PHONY : qmodule_pri/fast

#=============================================================================
# Target rules for targets named syncqt_build

# Build rule for target.
syncqt_build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 syncqt_build
.PHONY : syncqt_build

# fast build rule for target.
syncqt_build/fast:
	$(MAKE) $(MAKESILENT) -f qtbase\src\tools\syncqt\CMakeFiles\syncqt_build.dir\build.make qtbase/src/tools/syncqt/CMakeFiles/syncqt_build.dir/build
.PHONY : syncqt_build/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... test
	@echo ... benchmark
	@echo ... bootstrap_tools
	@echo ... docs
	@echo ... docs_qtbase
	@echo ... generate_docs
	@echo ... generate_docs_qtbase
	@echo ... host_tools
	@echo ... html_docs
	@echo ... html_docs_qtbase
	@echo ... install_docs
	@echo ... install_docs_qtbase
	@echo ... install_html_docs
	@echo ... install_html_docs_qtbase
	@echo ... install_qch_docs
	@echo ... install_qch_docs_qtbase
	@echo ... prepare_docs
	@echo ... prepare_docs_qtbase
	@echo ... qch_docs
	@echo ... qch_docs_qtbase
	@echo ... qmodule_pri
	@echo ... qpa_default_plugins
	@echo ... qpa_plugins
	@echo ... qt_plugins
	@echo ... qt_plugins_qtbase
	@echo ... qt_plugins_qtbase_recursive
	@echo ... sync_headers
	@echo ... syncqt_build
	@echo ... thirdparty_sync_headers
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

